"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { explorerTransactionUrl } from "../../lib/format";

interface Activity { id: string; kind: string; signature: string; occurredAt: string; finality: string; address: string; displayName: string | null }
interface Wallet { id: string; address: string; displayName: string | null; status: string; score: number | null; classification: string | null; transactionsStored: number }
interface Signal { id: string; type: string; level: string; score: number; detectedAt: string; symbol: string | null; mint: string }
interface Summary { monitoredWallets: number; eventsProcessed: number; transactions24h: number; signalsGenerated: number; recentActivity: Activity[]; wallets: Wallet[]; recentSignals: Signal[] }
interface System { nowMs: number; liveEnabled: boolean; database: { status: string; latencyMs: number }; redis: { status: string; latencyMs: number }; queues: { name: string; counts: { waiting: number; active: number; delayed: number; failed: number }; error: boolean }[]; workerHeartbeat: string | null; lastWebhook: string | null; latencyP95: number | null; subscriptionStatus: string | null; lastSyncOutcome: string | null; unresolvedFailures: number }

const short = (value: string, start = 7, end = 5) => value.length <= start + end + 3 ? value : `${value.slice(0, start)}…${value.slice(-end)}`;
const age = (value: string | null, nowMs: number) => value ? `${String(Math.max(0, Math.round((nowMs - Date.parse(value)) / 1000)))}s ago` : "No data";

export function CommandCenter({ summary, system }: { summary: Summary; system: System }) {
  const [paused, setPaused] = useState(false);
  const [filter, setFilter] = useState("ALL");
  const eventTypes = useMemo(() => ["ALL", ...new Set(summary.recentActivity.map((item) => item.kind))], [summary.recentActivity]);
  const activity = summary.recentActivity.filter((item) => filter === "ALL" || item.kind === filter);
  const selectedWallet = summary.wallets[0];
  const failedJobs = system.queues.reduce((total, queue) => total + queue.counts.failed, 0);
  return <div className="command-center">
    <header className="command-heading"><div><p className="eyebrow">Solana intelligence / live operations</p><h1>Command Center</h1><p>Real wallet activity, pipeline telemetry, and evidence-backed intelligence.</p></div><div className="heading-status"><Dot state={system.liveEnabled ? "online" : "unknown"} />{system.liveEnabled ? "Live ingestion active" : "Live ingestion disabled"}</div></header>
    <section className="metric-rail" aria-label="Key metrics"><Metric label="Monitored wallets" value={summary.monitoredWallets} note="Active tracked addresses" tone="cyan" /><Metric label="Live transactions · 24h" value={summary.transactions24h} note="Helius webhook source" tone="green" /><Metric label="Processed events" value={summary.eventsProcessed} note="All-time provider events" tone="violet" /><Metric label="Signals generated" value={summary.signalsGenerated} note={summary.signalsGenerated ? "Research evidence only" : "No signal evidence yet"} tone="amber" /><Metric label="Pipeline latency" value={system.latencyP95 === null ? "Unknown" : `${String(Math.round(system.latencyP95))}ms`} note="Live processing p95 · 1h" tone="cyan" /></section>
    <section className="command-grid">
      <Panel className="radar-panel" title="Live wallet radar" eyebrow="Activity topology" action={<span className="live-chip"><i /> scanning</span>}><Radar events={summary.recentActivity} wallets={summary.wallets} /></Panel>
      <Panel className="feed-panel" title="Live intel" eyebrow="Webhook-confirmed" action={<button className="ghost-button" type="button" onClick={() => { setPaused((value) => !value); }}>{paused ? "Resume" : "Pause"}</button>}><div className="feed-filters">{eventTypes.slice(0, 5).map((type) => <button className={filter === type ? "active" : ""} key={type} type="button" onClick={() => { setFilter(type); }}>{type.replaceAll("_", " ")}</button>)}</div><div className="live-feed" aria-live="polite">{paused ? <Empty title="Visual feed paused" text="Backend ingestion continues normally." /> : activity.length ? activity.slice(0, 10).map((item) => <FeedItem key={item.id} item={item} nowMs={system.nowMs} />) : <Empty title="No live activity" text={`Monitoring ${String(summary.monitoredWallets)} wallet${summary.monitoredWallets === 1 ? "" : "s"}. The radar remains active.`} />}</div></Panel>
      <Panel className="wallet-panel" title="Wallet intelligence" eyebrow="Primary monitored wallet">{selectedWallet ? <WalletSummary wallet={selectedWallet} latest={summary.recentActivity.find((item) => item.address === selectedWallet.address)} nowMs={system.nowMs} /> : <Empty title="No monitored wallets" text="Add a public Solana address to begin observation." />}</Panel>
    </section>
    <section className="lower-grid"><Panel title="System telemetry" eyebrow="Service health"><Telemetry system={system} failedJobs={failedJobs} /></Panel><Panel title="Recent signal evidence" eyebrow="Not predictions">{summary.recentSignals.length ? <div className="signal-list">{summary.recentSignals.slice(0, 5).map((signal) => <div key={signal.id}><span className={`signal-level ${signal.level.toLowerCase()}`}>{signal.level}</span><strong>{signal.symbol ?? short(signal.mint)}</strong><span>{signal.type.replaceAll("_", " ")}</span><b>{String(signal.score)}/100</b></div>)}</div> : <Empty title="No signal data" text="Signal intelligence becomes available after sufficient evidence is observed." />}</Panel><Panel title="System activity" eyebrow="Sanitized operational state"><Console system={system} /></Panel></section>
  </div>;
}

function Radar({ events, wallets }: { events: Activity[]; wallets: Wallet[] }) { return <div className="radar-stage"><div className="radar-field" role="img" aria-label={`${String(events.length)} recent live contacts`}><div className="radar-grid" /><div className="radar-sweep" /><div className="radar-core">DS</div>{events.slice(0, 8).map((event, index) => { const angle = (index * 137.5 + event.signature.charCodeAt(0)) * Math.PI / 180; const radius = 22 + (index % 4) * 11; return <a className={`radar-contact contact-${String(index % 4)}`} href={explorerTransactionUrl(event.signature)} key={event.id} rel="noreferrer" style={{ left: `${String(50 + Math.cos(angle) * radius)}%`, top: `${String(50 + Math.sin(angle) * radius)}%` }} target="_blank"><i /><span>{event.kind}</span></a>; })}{!events.length ? <p className="radar-empty">Awaiting live contacts</p> : null}</div><div className="scan-module"><div className="scan-title"><span>Scanning Solana</span><b>LIVE</b></div><Scan label="Helius stream" state={events.length ? "ACTIVE" : "READY"} /><Scan label="Wallet monitor" state={wallets.length ? "ACTIVE" : "IDLE"} /><Scan label="Transaction processor" state="READY" /><Scan label="Signal engine" state="UNAVAILABLE" /></div></div>; }
function Scan({ label, state }: { label: string; state: string }) { return <div className="scan-row"><i className={state === "UNAVAILABLE" ? "off" : ""} /><span>{label}</span><b>{state}</b></div>; }
function FeedItem({ item, nowMs }: { item: Activity; nowMs: number }) { return <article className="feed-item"><span className="event-icon">{item.kind.slice(0, 1)}</span><div><strong>{item.kind.replaceAll("_", " ")}</strong><p>{item.displayName ?? short(item.address)}</p></div><div className="feed-meta"><time>{age(item.occurredAt, nowMs)}</time><a href={explorerTransactionUrl(item.signature)} target="_blank" rel="noreferrer">{short(item.signature, 5, 4)} ↗</a></div></article>; }
function WalletSummary({ wallet, latest, nowMs }: { wallet: Wallet; latest: Activity | undefined; nowMs: number }) { return <div className="wallet-summary"><div className="wallet-identity"><div className="wallet-glyph">◎</div><div><strong>{wallet.displayName ?? short(wallet.address)}</strong><p>{short(wallet.address, 9, 7)}</p></div><span>{wallet.status}</span></div><dl><div><dt>Transactions analyzed</dt><dd>{wallet.transactionsStored}</dd></div><div><dt>Last live activity</dt><dd>{latest ? age(latest.occurredAt, nowMs) : "None observed"}</dd></div><div><dt>Classification</dt><dd>{wallet.classification?.replaceAll("_", " ") ?? "Insufficient evidence"}</dd></div><div title="Research score; not a probability."><dt>Research score ⓘ</dt><dd>{wallet.score === null ? "Unavailable" : `${String(wallet.score)}/100`}</dd></div></dl><p className="evidence-note">{wallet.score === null ? "Score unavailable — insufficient live allocation and copyability evidence." : "Evidence-based score; not a prediction of future returns."}</p><Link className="panel-link" href={`/wallets/${wallet.address}`}>Open wallet intelligence →</Link></div>; }
function Telemetry({ system, failedJobs }: { system: System; failedJobs: number }) { const worker = system.workerHeartbeat !== null && system.nowMs - Date.parse(system.workerHeartbeat) < 60_000; return <div className="telemetry-grid"><Service label="Database" state={system.database.status === "up" ? "ONLINE" : "OFFLINE"} note={`${String(system.database.latencyMs)}ms`} /><Service label="Redis / queues" state={system.redis.status === "up" && failedJobs === 0 ? "ONLINE" : "DEGRADED"} note={`${String(system.redis.latencyMs)}ms · ${String(failedJobs)} failed`} /><Service label="Ingestion worker" state={worker ? "ONLINE" : "UNKNOWN"} note={age(system.workerHeartbeat, system.nowMs)} /><Service label="Helius subscription" state={system.subscriptionStatus === "IN_SYNC" ? "ONLINE" : system.subscriptionStatus ?? "UNKNOWN"} note={system.lastWebhook ? `event ${age(system.lastWebhook, system.nowMs)}` : "No event observed"} /></div>; }
function Service({ label, state, note }: { label: string; state: string; note: string }) { return <div className="telemetry-row"><Dot state={state === "ONLINE" ? "online" : state === "OFFLINE" ? "offline" : "unknown"} /><span><strong>{label}</strong><small>{note}</small></span><b>{state}</b></div>; }
function Console({ system }: { system: System }) { const items = [{ time: system.lastWebhook, text: "Latest webhook observed" }, { time: system.workerHeartbeat, text: "Worker heartbeat recorded" }, { time: null, text: system.lastSyncOutcome ? `Subscription reconciled — ${system.lastSyncOutcome}` : "Subscription sync not observed" }]; return <div className="activity-console">{items.map((item) => <div key={item.text}><time>{item.time ? new Date(item.time).toISOString().slice(11, 19) : "--:--:--"}</time><span>{item.text}</span></div>)}{system.unresolvedFailures ? <div className="console-danger"><time>STATUS</time><span>{system.unresolvedFailures} unresolved failure(s)</span></div> : null}</div>; }
function Metric({ label, value, note, tone }: { label: string; value: string | number; note: string; tone: string }) { return <article className={`metric-card tone-${tone}`}><p>{label}</p><strong>{value}</strong><span>{note}</span><i /></article>; }
function Panel({ title, eyebrow, action, className = "", children }: { title: string; eyebrow: string; action?: React.ReactNode; className?: string; children: React.ReactNode }) { return <section className={`command-panel ${className}`}><header><div><p>{eyebrow}</p><h2>{title}</h2></div>{action}</header>{children}</section>; }
function Dot({ state }: { state: "online" | "offline" | "unknown" }) { return <i className={`status-dot ${state}`} aria-hidden="true" />; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty-state"><i>⌁</i><strong>{title}</strong><p>{text}</p></div>; }
